### ISSUE TITLE
Wrong number of cases in dataset

### ISSUE THREAD

**Issue by m-kruth** [2kruman/COVID19-NZ-known-cases#10]
Dataset does not have the same number of cases as the MOH's list of cases. This is likely a duplicated row somewhere.

**Comment by RapidCompiler** [comment]
I've taken care of this issue as well with my pull request. I didn't deliberately try to solve this issue as you self-assigned it and I respect that decision. But, this issue arose because of a mistake made by the health ministry of New Zealand and I found that out in the process of solving issue #11 . I've provided more description in my pull request. Apologies for any inconvenience caused.
