### ISSUE TITLE
Update data set 

### ISSUE THREAD

**Issue by RapidCompiler** [2kruman/COVID19-NZ-known-cases#17]
Update the data set to be factually correct as of 23-03-2020.

**Comment by m-kruth** [comment]
Hey I'm doing this right now FYI

**Comment by m-kruth** [comment]
https://github.com/2kruman/COVID19-NZ-known-cases/pull/18

**Comment by m-kruth** [comment]
Sorry I should have assigned it to myself. I will do this in the future when I'm working on something.

**Comment by m-kruth** [comment]
Aside from the new cases, I made the following changes too:

CHANGELOG (2020-03-22)

Updated flight details for case 8: changed source from France to Australia
Updated flight details for case 9 to include domestic flight number
Included flight details for case 13
Corrected arrival date for case 14 
Updated flight details for case 15. Included source country and date of arrival.
Updated travel destination for case 16.
Included source nation for case 17. Corrected arrival date.
Corrected travel source for case 18. Updated flight details.
Included flight details for case 19.
Corrected gender for case 21. Corrrected arrival date and source nation. Corrected flight details.
Corrected details for case 22, appears to have originally been case 21.
Added location and age for case 23.
Corrected orign of travel for case 24
Corrected locations for case 25.
Corrected age for case 26. Added all travel details.
Corrected flight details for case 27.
Corrected travel location details for case 28.
Assigned a new case to case 29.
Corrected flight details for case 31.
Corrected flight details for case 32.
Corrected age and flight details for case 33.
Corrected age and flight details for case 34.
Added flight details for case 39.
Added flight details for case 40.
Corrected gender and travel details for case 41.
Delete case 42

**Comment by RapidCompiler** [comment]
Good work! Btw, why the deletion of case 42 and the assignment of new case 29? And would you mind adding me as a collaborator on this repository?

Thanks and Regards, 
RapidCompiler.

**Comment by m-kruth** [comment]
Yep added you as a collaborator, please send your Kaggle account too so I can add you as a collaborator there too. 
- When comparing case 42 from the previous day to yesterdays data, I found that there were no similarities in any field. However case 43 was the same as 42 from the day before. It appeared that MOH deleted case 42. Perhaps it was a false positive? Or reassigned to another case number? It is hard to tell without a changelog from the MOH on what they are changing.
- Case 29 also suggested some shuffling of case numbers on MOH's part. There appeared to be no similarities between case 29 from 22-03-2020 and 23-03-2020. However case 28 was almost identical, with one extra field added. Furthermore case 30 from 23-03-2020 was identical to case 29 from 22-03-2020. This would indicate that they reassigned case 29 to a new case and bumped the old cases up by one.

Somewhat irrelevant speculation: I believe that case numbers may be based on when the individual was diagnosed. The shuffling is a symptom of the MOH receiving information asynchronously from different District Health Boards and then having to retrospectively figure out case numbers. Since they receive imperfect information, they are adding, removing and shuffling case numbers. Anyways just some idle speculation ;)

**Comment by RapidCompiler** [comment]
Cool. I don't think there can be any other reason!
